/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import modelo.negocio.SistemaVentas;
import modelo.personas.Vendedor;
import modelo.personas.Cliente;
import modelo.vehiculos.Vehiculo;
import modelo.transacciones.Cotizacion;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
/**
 *
 * @author usuario
 */
public class frmCrearCotizacion extends javax.swing.JFrame {
    private SistemaVentas sistema;
    private Vendedor vendedor;
    private Cotizacion cotizacionActual;    
    
    /**
     * Creates new form frmCrearCotizacion
     */
    public frmCrearCotizacion(SistemaVentas sistema, Vendedor vendedor) {
        this.sistema = sistema;
        this.vendedor = vendedor;
        initComponents();
        personalizarComponentes();
        cargarClientes();
        cargarVehiculos();
        cargarPromociones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlFormulario = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        lblPromocion = new javax.swing.JLabel();
        lblDetalles = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        cmbPromocion = new javax.swing.JComboBox<>();
        cmbVehiculo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        lblTotalValor = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitulo.setBackground(new java.awt.Color(102, 102, 255));
        pnlTitulo.setName("pnlTitulo"); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CREAR COTIZACIÓN");
        lblTitulo.setToolTipText("");
        lblTitulo.setName("lblTitulo"); // NOI18N

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlFormulario.setName("pnlFormulario"); // NOI18N

        lblCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblCliente.setText("Cliente:");
        lblCliente.setName("lblCliente"); // NOI18N

        lblVehiculo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        lblVehiculo.setText("Vehículo:");
        lblVehiculo.setName("lblVehiculo"); // NOI18N

        lblPromocion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPromocion.setForeground(new java.awt.Color(0, 0, 0));
        lblPromocion.setText("Promoción:");
        lblPromocion.setName("lblPromocion"); // NOI18N

        lblDetalles.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDetalles.setForeground(new java.awt.Color(0, 0, 0));
        lblDetalles.setText("Detalles:");
        lblDetalles.setName("lblDetalles"); // NOI18N

        lblTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("Total:");
        lblTotal.setName("lblTotal"); // NOI18N

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCliente.setName("cmbCliente"); // NOI18N
        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });

        cmbPromocion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPromocion.setName("cmbPromocion"); // NOI18N
        cmbPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPromocionActionPerformed(evt);
            }
        });

        cmbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVehiculo.setName("cmbVehiculo"); // NOI18N
        cmbVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVehiculoActionPerformed(evt);
            }
        });

        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        jScrollPane1.setViewportView(txtDetalles);

        lblTotalValor.setText("S/. 0.00");
        lblTotalValor.setName("lblTotalValor"); // NOI18N

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCliente)
                    .addComponent(lblVehiculo)
                    .addComponent(lblPromocion)
                    .addComponent(lblTotal)
                    .addComponent(lblDetalles))
                .addGap(27, 27, 27)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPromocion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                    .addComponent(lblTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehiculo)
                    .addComponent(cmbPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromocion)
                    .addComponent(cmbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addComponent(lblDetalles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(lblTotalValor)))
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblTotalValor.getAccessibleContext().setAccessibleName("lblTotalValor");

        pnlBotones.setName("pnlBotones"); // NOI18N

        btnGenerar.setBackground(new java.awt.Color(0, 204, 0));
        btnGenerar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar");
        btnGenerar.setName("btnGenerar"); // NOI18N
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnGenerar)
                .addGap(76, 76, 76)
                .addComponent(btnCancelar)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnCancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTitulo.getAccessibleContext().setAccessibleName("pnlTitulo");
        pnlFormulario.getAccessibleContext().setAccessibleName("pnlFormulario");
        pnlBotones.getAccessibleContext().setAccessibleName("pnlBotones");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        generarCotizacion();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void cmbPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPromocionActionPerformed
        // TODO add your handling code here:
        calcularTotal();
    }//GEN-LAST:event_cmbPromocionActionPerformed

    private void cmbVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVehiculoActionPerformed
        // TODO add your handling code here:
        calcularTotal();
    }//GEN-LAST:event_cmbVehiculoActionPerformed

    private void personalizarComponentes() {
        setSize(500, 550);
    }
    
    private void cargarClientes() {
        cmbCliente.removeAllItems();
        for (Cliente cli : sistema.getClientes()) {
            if (cli.isActivo()) {
                cmbCliente.addItem(cli.getDni() + " - " + cli.getNombreCompleto());
            }
        }
    }
    
    private void cargarVehiculos() {
        cmbVehiculo.removeAllItems();
        for (Vehiculo veh : sistema.getVehiculos()) {
            if (veh.getEstado().equals("DISPONIBLE")) {
                cmbVehiculo.addItem(veh.getCodigo() + " - " + veh.getMarca() + 
                                   " " + veh.getModelo());
            }
        }
    }
    
    private void cargarPromociones() {
        // Implementar si existe getPromociones() en SistemaVentas
    }
    
    private void calcularTotal() {
        if (cmbVehiculo.getSelectedIndex() >= 0) {
            String codigoVeh = ((String) cmbVehiculo.getSelectedItem()).split(" - ")[0];
            Vehiculo vehiculo = sistema.buscarVehiculo(codigoVeh);
            
            if (vehiculo != null) {
                double total = vehiculo.getPrecioBase();
                
                if (cmbPromocion.getSelectedIndex() > 0) {
                    total *= 0.9;
                }
                
                lblTotalValor.setText(String.format("S/. %.2f", total));
                actualizarDetalles(vehiculo, total);
            }
        }
    }
    
    private void actualizarDetalles(Vehiculo vehiculo, double total) {
        StringBuilder sb = new StringBuilder();
        sb.append("DETALLES DE LA COTIZACIÓN\n");
        sb.append("═══════════════════════════════════\n\n");
        sb.append("Vehículo: ").append(vehiculo.getMarca()).append(" ")
          .append(vehiculo.getModelo()).append("\n");
        sb.append("Año: ").append(vehiculo.getAnioFabricacion()).append("\n");
        sb.append("Color: ").append(vehiculo.getColor()).append("\n");
        sb.append("Tipo: ").append(vehiculo.getTipo()).append("\n");
        sb.append("Precio Base: S/. ").append(String.format("%.2f", vehiculo.getPrecioBase())).append("\n\n");
        sb.append("Vendedor: ").append(vendedor.getNombreCompleto()).append("\n");
        sb.append("═══════════════════════════════════\n");
        sb.append("TOTAL: S/. ").append(String.format("%.2f", total));
        
        txtDetalles.setText(sb.toString());
    }
    
    private void generarCotizacion() {
        if (cmbCliente.getSelectedIndex() == -1 || cmbVehiculo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar un cliente y un vehículo",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String dniCliente = ((String) cmbCliente.getSelectedItem()).split(" - ")[0];
        String codigoVeh = ((String) cmbVehiculo.getSelectedItem()).split(" - ")[0];
        
        Cliente cliente = sistema.buscarCliente(dniCliente);
        Vehiculo vehiculo = sistema.buscarVehiculo(codigoVeh);
        
        if (cliente != null && vehiculo != null) {
            cotizacionActual = vendedor.crearCotizacion(cliente, vehiculo);
            sistema.registrarCotizacion(cotizacionActual);
            
            JOptionPane.showMessageDialog(this,
                "Cotización generada exitosamente\nCódigo: " + cotizacionActual.getCodigo(),
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            
            dispose();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Ejemplo de uso - reemplazar
                SistemaVentas sistema = new SistemaVentas();
                Vendedor vendedor = new Vendedor("12345678", "Juan", "Pérez López", "jperez", "123");
                new frmCrearCotizacion(sistema, vendedor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton btnGenerar;
private javax.swing.JButton btnCancelar;
private javax.swing.JComboBox<String> cmbCliente;
private javax.swing.JComboBox<String> cmbPromocion;
private javax.swing.JComboBox<String> cmbVehiculo;
private javax.swing.JLabel lblTitulo;
private javax.swing.JLabel lblCliente;
private javax.swing.JLabel lblVehiculo;
private javax.swing.JLabel lblPromocion;
private javax.swing.JLabel lblDetalles;
private javax.swing.JLabel lblTotal;
private javax.swing.JLabel lblTotalValor;
private javax.swing.JPanel pnlTitulo;
private javax.swing.JPanel pnlFormulario;
private javax.swing.JPanel pnlBotones;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JTextArea txtDetalles;
    // End of variables declaration//GEN-END:variables
}
