/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.awt.*;
import modelo.negocio.SistemaVentas;
import modelo.transacciones.Venta;

/**
 *
 * @author usuario
 */
public class frmListaVentas extends javax.swing.JFrame {
    
    private SistemaVentas sistema;
    private JFrame framePadre;
    private DefaultTableModel modeloTabla;
    
    /**
     * Creates new form NewJFrame
     */
    public frmListaVentas(SistemaVentas sistema, JFrame padre) {
        this.sistema = sistema;
        this.framePadre = padre;
        initComponents();
        configuracionAdicional();
        cargarDatos();
    }

    
    private void configuracionAdicional() {
        setLocationRelativeTo(framePadre);
        // Inicializar el modelo a partir del JTable generado por el GUI builder
        modeloTabla = (DefaultTableModel) tblVentas.getModel();
        modeloTabla.setColumnIdentifiers(new String[]{"Código", "Fecha", "Cliente", "Vendedor", "Vehículo", "Total", "Saldo", "Estado"});
        tblVentas.setModel(modeloTabla);

        // Poner identificadores de columna (header) centrados
        JTableHeader header = tblVentas.getTableHeader();
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Centrar contenido de las columnas
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < modeloTabla.getColumnCount(); i++) {
           tblVentas.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Asegurar nombres identificadores adecuados para los botones (útil para pruebas/automatización)
       btnActualizar.setName("btnActualizar");
       btnCerrar.setName("btnCerrar");
       btnVerDetalle.setName("btnVerDetalle");
       btnActualizar.getAccessibleContext().setAccessibleName("btnActualizar");
       btnCerrar.getAccessibleContext().setAccessibleName("btnCerrar");
       btnVerDetalle.getAccessibleContext().setAccessibleName("btnVerDetalle");

        // Forzar que los botones muestren el color de fondo (Nimbus LAF lo ignora si no son opacos)
        Color verde = new Color(0, 204, 51);
        Color rojo  = new Color(255, 0, 0);
        Color azul  = new Color(0, 102, 255);

       btnActualizar.setBackground(verde);
       btnActualizar.setForeground(Color.WHITE);
       btnActualizar.setOpaque(true);
       btnActualizar.setContentAreaFilled(true);
       btnActualizar.setFocusPainted(false);
       btnActualizar.setBorderPainted(false);
       btnActualizar.setUI(new javax.swing.plaf.basic.BasicButtonUI());

       btnCerrar.setBackground(rojo);
       btnCerrar.setForeground(Color.WHITE);
       btnCerrar.setOpaque(true);
       btnCerrar.setContentAreaFilled(true);
       btnCerrar.setFocusPainted(false);
       btnCerrar.setBorderPainted(false);
       btnCerrar.setUI(new javax.swing.plaf.basic.BasicButtonUI());

       btnVerDetalle.setBackground(azul);
       btnVerDetalle.setForeground(Color.WHITE);
       btnVerDetalle.setOpaque(true);
       btnVerDetalle.setContentAreaFilled(true);
       btnVerDetalle.setFocusPainted(false);
       btnVerDetalle.setBorderPainted(false);
       btnVerDetalle.setUI(new javax.swing.plaf.basic.BasicButtonUI());

        // Listeners funcionales para los botones
       btnCerrar.addActionListener(evt -> dispose());       // Cerrar ventana
       btnVerDetalle.addActionListener(evt -> verDetalle());    // Ver detalle
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnVerDetalle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelTabla.setName("pnlTabla"); // NOI18N

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVentas.setName("tblVentas"); // NOI18N
        jScrollPane2.setViewportView(tblVentas);
        tblVentas.getAccessibleContext().setAccessibleName("tblVentas");

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTitulo.setBackground(new java.awt.Color(255, 153, 0));
        pnlTitulo.setName("pnlTitulo"); // NOI18N

        lblTitulo.setBackground(new java.awt.Color(230, 176, 9));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("LISTA DE VENTAS");
        lblTitulo.setName("lblTitulo"); // NOI18N

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(247, 247, 247))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(20, 20, 20))
        );

        btnActualizar.setBackground(new java.awt.Color(0, 204, 51));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setName("btnActualizar");
        btnActualizar.setActionCommand("btnActualizar");
        btnActualizar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.setName("btnCerrar");
        btnCerrar.setActionCommand("btnCerrar");
        btnCerrar.setPreferredSize(new java.awt.Dimension(100, 30));

        btnVerDetalle.setBackground(new java.awt.Color(0, 102, 255));
        btnVerDetalle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalle.setText("Ver Detalle");
        btnVerDetalle.setName("btnVerDetalle");
        btnVerDetalle.setActionCommand("btnVerDetalle");
        btnVerDetalle.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnVerDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlTitulo.getAccessibleContext().setAccessibleName("pnlTitulo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarDatos() {
        modeloTabla.setRowCount(0);
        if (sistema == null || sistema.getVentas() == null) {
            return;
        }
        for (Venta venta : sistema.getVentas()) {
            Object[] fila = {
                venta.getCodigo(),
                venta.getFecha(),
                venta.getCliente().getNombreCompleto(),
                venta.getVendedor().getNombreCompleto(),
                venta.getVehiculo().getMarca() + " " + venta.getVehiculo().getModelo(),
                String.format("S/. %.2f", venta.getMontoTotal()),
                String.format("S/. %.2f", venta.getSaldoPendiente()),
                venta.getEstadoPago()
            };
            modeloTabla.addRow(fila);
        }
    }
    
    private void verDetalle() {
        int filaSeleccionada = tblVentas.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                "Por favor seleccione una venta",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        String codigo = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
        for (Venta venta : sistema.getVentas()) {
            if (venta.getCodigo().equals(codigo)) {
                new DetalleVentaDialog(frmListaVentas.this, venta).setVisible(true);
                break;
            }
        }
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SistemaVentas sistema = new SistemaVentas();
                new frmListaVentas(sistema, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
}
