package gui;

import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Font;
import modelo.negocio.SistemaVentas;

/**
 * Formulario NetBeans para mostrar el inventario general
 */
public class InventarioFrame extends javax.swing.JFrame {
    
    private SistemaVentas sistema;
    private javax.swing.JFrame framePadre;
    private DefaultTableModel modeloTabla;
    
    /**
     * Constructor
     */
    public InventarioFrame(SistemaVentas sistema, javax.swing.JFrame padre) {
        this.sistema = sistema;
        this.framePadre = padre;
        initComponents();
        configurarTabla();
        cargarInventario();
        personalizarComponentes();
    }
    
    /**
     * Configuración adicional de la tabla
     */
    private void configurarTabla() {
        String[] columnas = {"Tipo", "Código", "Descripción", "Stock", "Estado"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaInventario.setModel(modeloTabla);
    }
    
    /**
     * Personalizar componentes después de initComponents()
     */
    private void personalizarComponentes() {
        // Panel título
        panelTitulo.setBackground(new Color(52, 73, 94));
        lblTitulo.setForeground(Color.WHITE);
        
        // Labels de resumen
        lblTotalVehiculos.setBackground(new Color(236, 240, 241));
        lblDisponibles.setBackground(new Color(236, 240, 241));
        lblVendidos.setBackground(new Color(236, 240, 241));
        
        // Tabla
        tablaInventario.getTableHeader().setBackground(new Color(52, 73, 94));
        tablaInventario.getTableHeader().setForeground(Color.WHITE);
        
        // Actualizar estadísticas
        actualizarEstadisticas();
    }
    
    /**
     * Cargar datos del inventario
     */
    private void cargarInventario() {
        modeloTabla.setRowCount(0);
        
        sistema.getVehiculos().forEach(veh -> {
            Object[] fila = {
                "VEHÍCULO",
                veh.getCodigo(),
                veh.getMarca() + " " + veh.getModelo() + " " + veh.getAnioFabricacion(),
                veh.obtenerStock(),
                veh.getEstado()
            };
            modeloTabla.addRow(fila);
        });
    }
    
    /**
     * Actualizar estadísticas del inventario
     */
    private void actualizarEstadisticas() {
        lblTotalVehiculos.setText("Total Vehículos: " + sistema.getVehiculos().size());
        lblDisponibles.setText("Disponibles: " + contarDisponibles());
        lblVendidos.setText("Vendidos: " + contarVendidos());
    }
    
    private int contarDisponibles() {
        return (int) sistema.getVehiculos().stream()
            .filter(v -> v.getEstado().equals("DISPONIBLE"))
            .count();
    }
    
    private int contarVendidos() {
        return (int) sistema.getVehiculos().stream()
            .filter(v -> v.getEstado().equals("VENDIDO"))
            .count();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelResumen = new javax.swing.JPanel();
        lblTotalVehiculos = new javax.swing.JLabel();
        lblDisponibles = new javax.swing.JLabel();
        lblVendidos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario General");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("INVENTARIO GENERAL");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelResumen.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelResumen.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        lblTotalVehiculos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotalVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalVehiculos.setText("Total Vehículos: 0");
        lblTotalVehiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotalVehiculos.setOpaque(true);
        panelResumen.add(lblTotalVehiculos);

        lblDisponibles.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisponibles.setText("Disponibles: 0");
        lblDisponibles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDisponibles.setOpaque(true);
        panelResumen.add(lblDisponibles);

        lblVendidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVendidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVendidos.setText("Vendidos: 0");
        lblVendidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblVendidos.setOpaque(true);
        panelResumen.add(lblVendidos);

        tablaInventario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Código", "Descripción", "Stock", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInventario.setRowHeight(25);
        jScrollPane1.setViewportView(tablaInventario);

        btnActualizar.setBackground(new java.awt.Color(52, 152, 219));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(149, 165, 166));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelResumen, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        cargarInventario();
        actualizarEstadisticas();
    }                                             

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        dispose();
    }                                         

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SistemaVentas sistema = new SistemaVentas();
                new InventarioFrame(sistema, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDisponibles;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalVehiculos;
    private javax.swing.JLabel lblVendidos;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelResumen;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tablaInventario;
    // End of variables declaration                   
}